terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2"
    }
  }
}


resource "local_sensitive_file" "env_ec2" {
  filename = "../dotenv/.env.ec2"
  content  = <<-EOT
    # This file is automatically generated by terraform.
    # Do not edit this file directly.
    # Instead, update your project-specific .env.local file
    JUMPBOX_HOST="${module.aws.jumpbox_host}"
  EOT
}

resource "local_sensitive_file" "env_redis" {
  filename = "../dotenv/.env.redis"
  content  = <<-EOT
    # This file is automatically generated by terraform.
    # Do not edit this file directly.
    # Instead, update your project-specific .env.local file
    REDIS_URL="${module.aws.redis_endpoints}"
  EOT
}

resource "local_sensitive_file" "env_ecs" {
  filename = "../dotenv/.env.ecs"
  content  = <<-EOT
    # This file is automatically generated by terraform.
    # Do not edit this file directly.
    # Instead, update your project-specific .env.local file
    FUNCTIONS_URL="${module.aws.unad_functions_api_url}"
    FUNCTIONS_API_KEY="${module.aws.unad_functions_api_key}"
  EOT
}

resource "local_sensitive_file" "env_rds" {
  filename = "../dotenv/.env.rds"
  content  = <<-EOT
    # This file is automatically generated by terraform.
    # Do not edit this file directly.
    # Instead, update your project-specific .env.local file
    DB_HOST="${module.aws.rds_cluster_endpoint}"
    DB_PASS="${module.aws.rds_cluster_password}"
    DB_PORT="${module.aws.rds_cluster_port}"
  EOT
}


resource "local_sensitive_file" "env_cognito" {
  filename = "../dotenv/.env.cognito"
  content  = <<-EOT
    # This file is automatically generated by terraform.
    # Do not edit this file directly.
    # Instead, update your project-specific .env.local file
    COGNITO_CLIENT_ID="${module.aws.cognito_client_id}"
    COGNITO_CLIENT_SECRET="${module.aws.cognito_client_secret}"
    COGNITO_POOL_DOMAIN="${module.aws.cognito_pool_domain}"
    COGNITO_POOL_DOMAIN_ID="${module.aws.cognito_pool_domain_id}"
    COGNITO_POOL_ENDPOINT="${module.aws.cognito_pool_endpoint}"
    COGNITO_USER_POOL_ID="${module.aws.cognito_pool_id}"
    TEST_USER_EMAIL="${module.aws.test_user_credentials.username}"
    TEST_USER_PASSWORD="${module.aws.test_user_credentials.password}"
    TEST_USER_ID="${module.aws.test_user_credentials.userId}"
  EOT
}
