variable "AWS_REGION" {}
variable "AWS_ACCESS_KEY_ID" {}
variable "AWS_SECRET_ACCESS_KEY" {}
variable "GITHUB_TOKEN" {}
variable "SIGNUP_DNS_ZONE" {}
variable "SUBSCRIBE_DNS_ZONE" {}
variable "PORTAL_DNS_ZONE" {}
variable "ENVIRONMENT" {}
variable "VPC_CIDR" {}
