userdb: {
  label: "userdb"
  label.near: "top-center"
  shape: cylinder
  icon: ./icons/postgres.svg
  icon.near: "bottom-center"
  style.multiple: true
}
paymentdb: {
  label: "paymentdb"
  label.near: "top-center"
  shape: cylinder
  icon: ./icons/postgres.svg
  icon.near: "bottom-center"
  style.multiple: true
  link: /data/paymentdb
}
productdb: {
  label: "productdb"
  label.near: "top-center"
  shape: cylinder
  icon: ./icons/postgres.svg
  icon.near: "bottom-center"
  style.multiple: true
}
