// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Nudges.Data.Users;

#nullable disable

namespace Nudges.Data.Users.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20251126034430_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClientSubscriber", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscriber_id");

                    b.HasKey("ClientId", "SubscriberId")
                        .HasName("client_subscriber_pkey");

                    b.HasIndex(new[] { "SubscriberId" }, "idx_client_subscriber_subscriber_id");

                    b.ToTable("client_subscriber", (string)null);
                });

            modelBuilder.Entity("Nudges.Data.Users.Models.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("admin_pkey");

                    b.ToTable("admin", (string)null);
                });

            modelBuilder.Entity("Nudges.Data.Users.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CustomerId")
                        .HasColumnType("character varying")
                        .HasColumnName("customer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("slug")
                        .HasDefaultValueSql("''::character varying");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("character varying")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("client_pkey");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("idx_client_slug");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("Nudges.Data.Users.Models.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("subscriber_pkey");

                    b.ToTable("subscriber", (string)null);
                });

            modelBuilder.Entity("Nudges.Data.Users.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("JoinedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("locale")
                        .HasDefaultValueSql("'en-US'::character varying");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumberEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number_encrypted");

                    b.Property<string>("PhoneNumberHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phone_number_hash");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("user_pkey");

                    b.HasIndex("PhoneNumberHash")
                        .IsUnique()
                        .HasDatabaseName("user_phone_number_hash_key");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("ClientSubscriber", b =>
                {
                    b.HasOne("Nudges.Data.Users.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("client_subscriber_client_id_fkey");

                    b.HasOne("Nudges.Data.Users.Models.Subscriber", null)
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("client_subscriber_subscriber_id_fkey");
                });

            modelBuilder.Entity("Nudges.Data.Users.Models.Admin", b =>
                {
                    b.HasOne("Nudges.Data.Users.Models.User", "IdNavigation")
                        .WithOne("Admin")
                        .HasForeignKey("Nudges.Data.Users.Models.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("admin_user_id_fkey");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Nudges.Data.Users.Models.Client", b =>
                {
                    b.HasOne("Nudges.Data.Users.Models.User", "IdNavigation")
                        .WithOne("Client")
                        .HasForeignKey("Nudges.Data.Users.Models.Client", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("client_user_id_fkey");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Nudges.Data.Users.Models.Subscriber", b =>
                {
                    b.HasOne("Nudges.Data.Users.Models.User", "IdNavigation")
                        .WithOne("Subscriber")
                        .HasForeignKey("Nudges.Data.Users.Models.Subscriber", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("subscriber_user_id_fkey");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Nudges.Data.Users.Models.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Client");

                    b.Navigation("Subscriber");
                });
#pragma warning restore 612, 618
        }
    }
}
