title: |`md
  # 30,000ft View
  This is the 30,000ft view of the Nudges system
`|

ElastiCache: {
  shape: image
  icon: ./icons/elasticache.svg
}

Twilio: {
  label: ""
  shape: image
  icon: ./icons/twilio.svg
}

Stripe: {
  label: ""
  shape: image
  icon: ./icons/stripe.svg
}

RDS: {
  icon: ./icons/aurora.svg

  cluster: {
    link: /services/rds
    shape: cylinder
    icon: ./icons/postgres.svg
    icon.near: "bottom-center"
    style.multiple: true
  }
}

ECS: {
  icon: ./icons/ecs.svg

  nudges-cluster: {
    link: /aws/ecs
    shape: parallelogram
    icon: ./icons/ecs-instance.svg
    style.multiple: true
  }
}

Cloudfront: {
  shape: image
  icon: ./icons/cloudfront.svg
}
Cloudwatch: {
  shape: image
  icon: ./icons/cloudwatch.svg
}

S3: {
  link: /aws/s3
  icon: ./icons/s3.svg
  admin-ui: {
    shape: page
    icon: ./icons/react.svg
  }
  signup-site: {
    shape: page
    icon: ./icons/react.svg
  }
}

MSK: {
  shape: image
  icon: ./icons/msk.svg
}

Admin: {
  shape: image
  icon: ./icons/admin-user.svg
}

Clients: {
  shape: image
  icon: ./icons/users.svg
}

Subscribers: {
  shape: image
  icon: ./icons/users.svg
}

ECS -> RDS
ECS -> ElastiCache
Cloudwatch -> ECS
MSK -> ECS: Event Stream

S3 -> Cloudfront
Cloudfront -> ECS: Authentication
Admin -> S3.admin-ui: portal.nudges.tech
Clients -> S3.signup-site: signup.nudges.tech
Subscribers -> S3.signup-site: nudges.me/id_here

Twilio -> ECS: Webhooks
Stripe -> ECS: Product Sync
