webhooks: {
  shape: image
  icon: ./icons/docker.svg
}
signup-site: {
  shape: image
  icon: ./icons/docker.svg
}
user-api: {
  shape: image
  icon: ./icons/docker.svg
}
product-api: {
  shape: image
  icon: ./icons/docker.svg
}
payment-api: {
  shape: image
  icon: ./icons/docker.svg
}
graphql-gateway: {
  shape: image
  icon: ./icons/docker.svg
}
auth-api: {
  shape: image
  icon: ./icons/docker.svg
}
