# https://icons.terrastruct.com/ for icons

ElastiCache: {
  shape: image
  icon: ./icons/elasticache.svg
}

Twilio: {
  label: ""
  shape: image
  icon: ./icons/twilio.svg
}

Stripe: {
  label: ""
  shape: image
  icon: ./icons/stripe.svg
}

RDS: {
  icon: ./icons/aurora.svg
  label: "RDS"

  cluster: {
    shape: cylinder
    icon: ./icons/postgres.svg
    icon.near: "bottom-center"
    style.multiple: true
  }
}

webhooks: {
  shape: image
  icon: ./icons/ecs-instance.svg
}
signup-site: {
  shape: image
  icon: ./icons/ecs-instance.svg
}
user-api: {
  shape: image
  icon: ./icons/ecs-instance.svg
}
product-api: {
  shape: image
  icon: ./icons/ecs-instance.svg
}
payment-api: {
  shape: image
  icon: ./icons/ecs-instance.svg
}
graphql-gateway: {
  shape: image
  icon: ./icons/ecs-instance.svg
}
auth-api: {
  shape: image
  icon: ./icons/ecs-instance.svg
}
