name: PR checks for admin-ui

on:
  pull_request:
    branches:
      - main
    paths:
      - 'web/admin-ui/**'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build packages
        run: npm run build -- --workspace=packages/db-models
      
      - name: Run tests
        run: npm test -- --workspace=web/admin-ui
      